### ISSUE TITLE
Create property-customized-types

### ISSUE THREAD

**Issue by matteocannaviccio** [3rr4t1c/knowledge-graph-augmentation#1]
Abbiamo visto che i tipi sono abbastanza importanti per Lector. Utilizzando tipi troppo specifici pero si rischia di disperdere troppo l'informazione sui patterns. Un'idea può essere quella di utilizzare l'ontologia dei tipi di DBpedia per semplificare i tipi in base alla relazione. 

Ad esempio:
- `workAt` possiamo semplificare i tipi a **Person**-**Organization**
- `politicalParty` possiamo essere piu specifici e considerare **Person**-**PoliticalParty**

**Comment by 3rr4t1c** [comment]
Ok, penso di aver capito. Nel file `types_ontology.tsv` c'è una lista di entità con i loro rispettivi tipi. Per poter semplificare i tipi serve la gerarchia in `types_hyerarchy.tsv` e poter risalire ai tipi parent per ciascuna entità fino al livello desiderato.
