### ISSUE TITLE
Easily create Lector model 

### ISSUE THREAD

**Issue by matteocannaviccio** [3rr4t1c/knowledge-graph-augmentation#2]
Per fare diversi esperimenti con le diverse scelte che facciamo dobbiamo essere "agili" nella creazione del modello di Lector. 
Un modello di Lector può essere creato secondo alcuni parametri: dobbiamo poter essere rapidi nel creare un modello secondo i parametri che scegliamo.

Ti consiglio di farlo tramite un file di configurazione (o dei parametri come il `notypes` che hai usato) che passiamo come input al creatore del modello (insieme a labeled_triples e unlabeled_triples presumo). 

Per ora possiamo scegliere sui tipi:
- `no-types`
- `property-specific-types`
- `property-customized-types`: issue https://github.com/3rr4t1c/knowledge-graph-augmentation/issues/1

Penso che ci aggiungeremo anche altri parametri.

**Comment by 3rr4t1c** [comment]
Ok, questa è una delle prossime cose che volevo sistemare. Ci sono però alcune considerazioni:

- `no-types` non è solo un iperparametro proprio dell'oggetto Lector. Sarebbe interessante poter eseguire l'addestramento con il supporto dei tipi (per creare le model triples) ed invece valutare l'estrazione con match solo sulle phrases. Penso si possa settare come flag di default all'inizializzazione e poi eventualmente forzare il comportamento all'estrazione inserendo un nuovo parametro.
- `property-specific-types` immagino sia l'opzione per usare la gerarchia di tipi originale
- `property-customized-types` dovrebbe essere riferita sia alla generalizzazione dei tipi originali che a quelli artificiali inferiti in base alla relazione?
- `subsamp` regola la percentuale di unlabeled triples come nel progetto originale e devo spostarla negli iperparametri inizializzati dal costruttore, adesso viene passata direttamente al metodo train.

> Ti consiglio di farlo tramite un file di configurazione (o dei parametri come il notypes che hai usato) che passiamo come input al creatore del modello (insieme a labeled_triples e unlabeled_triples presumo).

Si, si può fare sia tramite file di configurazione che come parametri passati allo script in stile CLI... pensavo di farli entrambe.

Il creatore istanzia un modello vuoto, riceve al max qualche iperparametro. Alla funzione di train si passano le text triples ed il knowledge graph che ricostruiscono le labeled e le unlabeled e da queste poi viene creata model triples. In pratica è tutta la pipeline completa di Lector come mostrata nella overview. Manca solo l'elaborazione delle phrases che vengono prese senza place holders. Comunque questo non impedisce di usare labeled e unlabeled custom saltando la fase distant supervision.

**Comment by matteocannaviccio** [comment]
Ottimo. Ho creato la issue in questo modo solo per essere sicuro che avevi pensato a queste flessibilità a livello di codice e vedo che lo hai fatto. Valuta tu se è piu comodo un config file o meno. 

Penso che la funzione che fa matching sui nuovi fatti prenda altri parametri in input (e.g. matching esatto/approssimato) tra cui di nuovo il metodo dei tipi.

property-customized-types è la funzione con i tipi artificiali. La type hierarchy serve a risalire ad un possibile tipo predefinito quando valutiamo ogni singola tripla (che invece presenta un tipo specifico). Pensa a come applicheresti questa funzione in fase di matching di nuovi fatti...
