### ISSUE TITLE
Set up evaluation for Lector

### ISSUE THREAD

**Issue by matteocannaviccio** [3rr4t1c/knowledge-graph-augmentation#3]
E' necessaria una valutazione un po rigorosa di Lector indipendentemente dal dataset che utilizziamo. Questa issue ha un duplice obiettivo: 

- [ ] (1) rappresentare ogni dataset che consideriamo in un formato generale (indipendente dal dataset)

- [ ] (2) creare un "evaluator" che valuti i risultati di lector.

(1) conviene scrivere del codice che sia abbastanza flessibile e indipendente dallo specifico dataset. In generale un dataset ci aspettiamo che contenga una frase annotata con delle triple (soggetto, relazione, oggetto), quindi in sostanza una lista di triple. Questa lista di triple si riduce ulteriormente quando consideriamo un sottoinsieme di relazioni (conviene essere flessibili e dare la lista di relazioni come input). 

(2) valutiamo precision e recall in questo modo (sostituisci la parola "entity relations" con "triple"):
![Screen Shot 2021-01-29 at 9 37 54 AM](https://user-images.githubusercontent.com/3764239/106308536-b37bc380-6215-11eb-9096-d288db8fce03.png)

**Comment by 3rr4t1c** [comment]
(1) Non ho ben capito cosa intendi, il formato del dataset accettato per fare test è lo stesso delle text triples usate per l'addestramento insieme al knowledge graph. Sono semplicemente file .tsv che devono avere i campi ordinati in un preciso ordine: <phrase> <entity1_id> <entity1_type> <entity2_id> <entity2_type>. Qualsiasi altro tipo di dataset, anche lo stesso con le colonne cambiate di posto potrebbe causare un errore. 
Intendi forse implementare una funzione di check automatico per il formato?

(2) Avevo già implementato il metodo di classe "evaluate" che prende in input una lista di text triples ed una ground truth con le etichette corrette, effettua l'estrazione e confronta i risultati. Eseguendo lo script vengono anche stampate precision, recall e f1-Measure per l'esempio banale creato a mano.
Intendo comunque rivederne alcune parti...

(Per text triples intendo l'omonima tabella che ho inserito nell'overview)
